### ISSUE TITLE
Unix depenency conflict

### ISSUE THREAD

**Issue by yikelu** [roman/testloop#2]
My current unix version is 2.7.0.0, which conflicts with testloop's requirements.

$ cabal install testloop
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: testloop-0.1.1.0 (user goal)
next goal: unix (dependency of testloop-0.1.1.0)
rejecting: unix-2.7.0.1/installed-23f..., 2.7.0.1, 2.7.0.0 (conflict: testloop
=> unix>=2.2.0.0 && <2.7)
rejecting: unix-2.6.0.1, 2.6.0.0 (conflict: base==4.7.0.0/installed-018...,
unix => base>=4.2 && <4.7)
rejecting: unix-2.5.1.1, 2.5.1.0 (conflict: base==4.7.0.0/installed-018...,
unix => base>=4.2 && <4.6)
rejecting: unix-2.5.0.0 (conflict: base==4.7.0.0/installed-018..., unix =>
base>=4.2 && <4.5)
rejecting: unix-2.4.2.0, 2.4.1.0 (conflict: base==4.7.0.0/installed-018...,
unix => base>=4.2 && <4.4)
rejecting: unix-2.4.0.2, 2.4.0.1 (conflict: base==4.7.0.0/installed-018...,
unix => base>=4.2 && <4.3)
rejecting: unix-2.4.0.0 (conflict: base==4.7.0.0/installed-018..., unix =>
base>=4.1 && <4.3)
trying: unix-2.3.2.0
next goal: hint (dependency of testloop-0.1.1.0)
rejecting: hint-0.4.1.0, 0.4.0.0 (conflict: testloop => hint==0.3.*)
trying: hint-0.3.3.7
next goal: ghc (dependency of hint-0.3.3.7)
rejecting: ghc-7.8.2/installed-a02... (conflict: unix==2.3.2.0, ghc =>
unix==2.7.0.1/installed-23f...)
Dependency tree exhaustively searched.

**Comment by arno-h** [comment]
The proplem is that testloop pins hint == 0.3.*.
If you change the cabal file, so that build-depends contains hint >= 0.3, the package builds.

There's a warning during the build, but that can be ignored (at the time of this writing):
 src\System\TestLoop\Util.hs:10:1: Warning:
    Local definition of `join' clashes with a future Prelude name - this will become an error in GHC 7.10, under the Applicative-Monad Proposal.

**Comment by roman** [comment]
Do you mind creating a PR with the change on cabal? I'll do the new release on hackage
